#server:
#  port: 8000
#
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#
#management:
#  tracing:
#    sampling:
#      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employee/** # Capitalized "Path"
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/v1/department/** # Capitalized "Path"
  config:
    import: optional:configserver:http://localhost:7090 # Corrected syntax
